version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: protocol_generator_postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    env_file: ".env"
    volumes:
      - protocol_generator_db:/var/lib/postgresql/data

volumes:
  protocol_generator_db:
    name: protocol_generator_db
    driver: local
